### ISSUE TITLE
$completeURL being changed to all lower case

### ISSUE THREAD

**Issue by dgets** [dgets/snag-eps#8]
This one is interesting.  Never bumped into this in shell script before...

When `$completeURL` is utilized on the command line, the entire string has had all uppercase letters shifted to lower case.  Other than that it appears to be building the command line perfectly well.

**Comment by dgets** [comment]
See also commit: 8c45c1a5a6a1edd77de691850c2aaa0e2062110b

**Comment by deutrino** [comment]
curious if some commas are getting in there or something is otherwise causing this to happen .. https://stackoverflow.com/questions/21310685/reading-arguments-in-shell-script

maybe try wrapping shit in quotes or something like that? echo the component variables before they're concatenated together to see what case they are? concatenate with multiple lines of code?

**Comment by quique** [comment]
It works fine in my system.
Beware that the server name is case insensitive.
Ie, `Www.FooBar.Com` and `www.foobar.com` both work fine.

However, the path inside the server is case sensitive.
I.e., `www.foo.com/FooBar` and `www.foo.com/foobar` are two distinct URLs.

As said, on my system the script doesn't mess this up.  What arguments are you passing?

**Comment by dgets** [comment]
@deutrino: I really don't think that there's any punctuation getting in there.  When I was doing things with real-world URL snippets, earlier, I know that the URLs had been sanitized with %20, etc, etc.  So I wasn't sure if maybe that punctuation was having some repercussions.

@quique: Yup, I'm down with the case sensitivity contexts.  :)

I just did a little bit of work here, and I'm producing some debugging output...  Let me show what I'm getting so far here:
```
khelair@orrah:~/src/sh/snag-eps$ ./snag-eps.sh godOuah LordyIHopeHeDid 03 6
--2017-10-12 00:00:52--  http://godouah03lordyihopehedid/
Resolving godouah03lordyihopehedid (godouah03lordyihopehedid)... 198.105.244.23, 198.105.254.23
Connecting to godouah03lordyihopehedid (godouah03lordyihopehedid)|198.105.244.23|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html’

index.html              [ <=>                ]     344  --.-KB/s    in 0s      

2017-10-12 00:00:52 (64.4 MB/s) - ‘index.html’ saved [344]

--2017-10-12 00:00:52--  http://godouah04lordyihopehedid/
Resolving godouah04lordyihopehedid (godouah04lordyihopehedid)... 198.105.244.23, 198.105.254.23
Connecting to godouah04lordyihopehedid (godouah04lordyihopehedid)|198.105.244.23|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html.1’

index.html.1            [ <=>                ]     344  --.-KB/s    in 0s      

2017-10-12 00:00:52 (62.7 MB/s) - ‘index.html.1’ saved [344]

--2017-10-12 00:00:52--  http://godouah05lordyihopehedid/
Resolving godouah05lordyihopehedid (godouah05lordyihopehedid)... 198.105.244.23, 198.105.254.23
Connecting to godouah05lordyihopehedid (godouah05lordyihopehedid)|198.105.244.23|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html.2’

index.html.2            [ <=>                ]     344  --.-KB/s    in 0s      

2017-10-12 00:00:53 (61.8 MB/s) - ‘index.html.2’ saved [344]

--2017-10-12 00:00:53--  http://godouah06lordyihopehedid/
Resolving godouah06lordyihopehedid (godouah06lordyihopehedid)... 198.105.244.23, 198.105.254.23
Connecting to godouah06lordyihopehedid (godouah06lordyihopehedid)|198.105.244.23|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html.3’

index.html.3            [ <=>                ]     344  --.-KB/s    in 0s      

2017-10-12 00:00:53 (67.7 MB/s) - ‘index.html.3’ saved [344]
```
As you can see above, the concatenated string was in all lower case...

I'm going to see what happens when I echo the arguments before concatenation (see commit: 3b516f4), too:

```
khelair@orrah:~/src/sh/snag-eps$ ./snag-eps.sh godOuah LordyIHopeHeDid 03 6
godOuah - LordyIHopeHeDid - 03 - 6
```

So the problem must lie with the concatenation, or something _really_ close to it.

**Comment by dgets** [comment]
So, in the _wget_ line, if the strings to concatenate are quoted, it shifts everything to lower case.  Otherwise it's fine.  Strange things...

**Comment by deutrino** [comment]
I require answers

**Comment by dgets** [comment]
Yeah that's a bit of a puzzling one...

**Comment by quique** [comment]
Guys, it is quite simple.

Look at your command:
`./snag-eps.sh godOuah LordyIHopeHeDid 03 6`

This produces the URL `http://godouah03lordyihopehedid/`.  What are the servername and the path in there?  As you can see, there is no path: the whole string is the servername.  And as you all know, servernames are case insensitive.

Put some slashes in the arguments and you will see it clearly.

**Comment by dgets** [comment]
@quique: The URL's server and path components are not processed any differently, actually.  Testing it with that particular data was relevant for either the server or pathname.  The only difference, if a path were specified, would be that the applicable string(s) would've contained one or more slashes.

I wanted to preserve original case across the entire URL; I understand that the server component is not case sensitive, this was more just of a style preference.  That, and, of course, I could then process both the URL & the pathname aspects in the same manner...

Anyhoo, any ideas why the quoting bit would cause this?

**Comment by quique** [comment]
I'm afraid I don't get you.
I think the current behaviour is the expected behaviour:
```
./snag-eps.sh WwW.Foo.Com/Foobar/Baz .mp4 01 2
--2017-10-14 10:41:13--  http://www.foo.com/Foobar/Baz01.mp4
[...]
```
You don't have to process the host and the pathname any differently.

The original case is preserved through the whole script.  It is `wget` who changes the hostname to lowercase:
```
$ wget WwW.Foo.Com/Foobar/Baz.mp4
--2017-10-14 10:44:35--  http://www.foo.com/Foobar/Baz.mp4
```
